# Project Information
site_name: Arabian vACC - Library
site_description: Access essential tools and information for pilots and controllers in the Arabian vACC. From charts and procedures to training and sector files, everything you need for a seamless and realistic experience on the VATSIM network is here.
site_url: https://library.arabian-vacc.com
repo_url: https://github.com/arabian-vacc/library
repo_name: arabian-vacc/library
edit_uri: ""
copyright: ""

# Project Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  font:
    text: Mulish
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Go to the dark side..
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Shine some light on this!
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: fontawesome/solid/headset

# Project Plugins
plugins:
  - search:
      lang: en
  - awesome-pages: {}
  - git-revision-date-localized:
      type: date
      strict: false
  - external-markdown: {}
  - glightbox:
      touchNavigation: true
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: false

# Project Styling
extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  - stylesheets/navigation.css

# Project Extra / Social Links
extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/arabianvacc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Fk9Wspw
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/arabianvacc
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/arabianvacc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/arabianvacc
    - icon: fontawesome/brands/github
      link: https://github.com/arabian-vacc

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - meta: {} # Add front matter to a document
  - admonition: {} # Makes things pretty
  - pymdownx.superfences: {} # Nestled code
  - attr_list: {} # Add HTML attributes and CSS classes to Markdown elements
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.details: {} # Additional features to admonition
  - pymdownx.caret: {} # Formatting Extension
  - pymdownx.critic: {} # Alternate Formatting Extension
  - pymdownx.mark: {} # Formatting Extension
  - pymdownx.tilde: {} # Formatting Extension
  - pymdownx.keys: {} # Visual keyboard keys extension
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Allows emoji style inline embeds for icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html: {} #enables the use of image figures
  - abbr: {}
  - pymdownx.snippets: {}

# Project Javascript
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6